# headscale configuration file
# The url clients will connect to.
server_url: https://headscale.ipv4.name

# Address to listen to / bind to on the server
listen_addr: 0.0.0.0:8080

# Address to listen to /metrics
metrics_listen_addr: 0.0.0.0:9090

# Address to listen for gRPC
grpc_listen_addr: 0.0.0.0:50443

# Allow the gRPC admin interface to run in INSECURE mode
grpc_allow_insecure: true

# The Noise section includes specific configuration for the TS2021 Noise protocol
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# List of IP prefixes to allocate tailaddresses from
prefixes:
  v6: ""
  v4: 100.64.0.0/10
  #allocation: sequential

# DERP is a relay system that Tailscale uses when a direct connection cannot be established
# config.yaml 中的 DERP 部分 - 仅使用自建 DERP
derp:
  server:
    enabled: false
  #urls: []  # 明确设置为空数组，而不是留空
  paths:
    - /etc/headscale/derp.yaml
  auto_update_enabled: true
  update_frequency: 24h
  stun_listen_addr: "derper:3478"

# Disables the automatic check for headscale updates on startup
disable_check_updates: false

# Time before an inactive ephemeral node is deleted
ephemeral_node_inactivity_timeout: 30m

# Database configuration
database:
  type: postgres
  # # Postgres config
  # Please note that using Postgres is highly discouraged as it is only supported for legacy reasons.
  # See database.type for more information.
  postgres:
    # If using a Unix socket to connect to Postgres, set the socket path in the 'host' field and leave 'port' blank.
    host: pg
    port: 5432
    name: tailscale
    user: tailscale
    pass: tailscale
    max_open_conns: 10
    max_idle_conns: 10
    conn_max_idle_time_secs: 3600

    # If other 'sslmode' is required instead of 'require(true)' and 'disabled(false)', set the 'sslmode' you need
    # in the 'ssl' field. Refers to https://www.postgresql.org/docs/current/libpq-ssl.html Table 34.1.
    ssl: false

### TLS configuration
# Let's encrypt / ACME
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""
tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"

## Use already defined certificates:
tls_cert_path: ""
tls_key_path: ""

# Logging configuration
log:
  format: json
  level: info

## Policy
policy:
  mode: database
  path: ""

## DNS configuration
dns:
  # 关闭 MagicDNS
  magic_dns: true
  # 由于关闭了 MagicDNS，base_domain 将不生效
  base_domain: tailnet.local
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    split: {}
  search_domains: []
  extra_records: []

# Unix socket used for the CLI to connect without authentication
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
routes:
  enabled: true
# 允许子网路由广播
subnet_router:
  enabled: true
  allow_advertise_routes: true
# Logtail configuration
logtail:
  enabled: false

# Randomize client port
randomize_client_port: true
# 允许出口节点功能
enable_routing: true
