# config/derp.yaml - 自建 DERP 服务器配置
regions:
  900:
    regionid: 900
    regioncode: "custom"
    regionname: "Self-hosted DERP"
    nodes:
      - name: "derp-ipv4"
        regionid: 900
        hostname: "derp.domain.com"        # 替换为您的实际域名
        ipv4: "154.89.xxx.31"     # 替换为您服务器的公网 IP
        stunport: 3478
        stunonly: false
        derpport: 443                     # HTTPS 端口
        insecurefordevelopment: false     # 生产环境设为 false