server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "abcdefghijklmnopqrstuvwxyz123456"
  cookie_secure: false

headscale:
  url: "http://headscale:8080"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true

integration:
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
  kubernetes:
    enabled: false
    pod_name: "headscale"        # 必需字段
    validate_manifest: true      # 必需字段
  proc:
    enabled: false
